### ISSUE TITLE
table is larger in firefox

### ISSUE THREAD

**Issue by norveclibalikci** [ituis17/a1-UgurONAL#1]
![image](https://user-images.githubusercontent.com/9158766/31844766-799ee500-b603-11e7-82aa-4903d8ef0293.png)
In full HD resolution and Firefox browser, there is a bit of odd here. Viewing website in Chrome may be delusional.

**Comment by UgurONAL** [comment]
Thank you for your comment. The problem should be solved. If it still has the same issue on your browser, feel free to notify me again.
